blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/cnrai/pave-dist/wiki
    about: Check the wiki for guides and documentation
  - name: Discussions
    url: https://github.com/cnrai/pave-dist/discussions
    about: Ask questions and share ideas in Discussions
